spring.application.name=proyectos
spring.datasource.url=jdbc:postgresql://localhost:5432/proyectos_db2
spring.datasource.username=postgres
spring.datasource.password=6545319Aa@
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true